Repository microsoft/calculator, pull requests merged in 2019-07, with the labels that each got.

#555 Date difference: display the difference in days (only) when we aren't able to calculate the difference in days/weeks/months..
  src/CalcViewModel/Common/DateCalculator.cpp
  src/CalcViewModel/Common/DateCalculator.h
  src/CalcViewModel/DateCalculatorViewModel.cpp
  src/Calculator/Resources/en-US/Resources.resw
  src/CalculatorUnitTests/DateCalculatorUnitTests.cpp
Labels: Codebase Quality, fixing approved issue

#491 Applying NR 1 to CalculatorVector.h
  src/CalcManager/CalculatorVector.h
Labels: Codebase Quality, Waiting For Update

#259 Use the current locale to sort country names
  src/CalcViewModel/Common/LocalizationService.cpp
  src/CalcViewModel/Common/LocalizationService.h
  src/CalcViewModel/DataLoaders/CurrencyDataLoader.cpp
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj.filters
  src/CalculatorUnitTests/LocalizationServiceUnitTests.cpp
Labels: fixing approved issue

#576 Removed need for trimIdx and fDigitsFound, resulting in less code.
  src/CalcManager/ExpressionCommand.cpp
Labels: Codebase Quality

#432 Make History and Memory list items context menu accessible using keyboard
  src/Calculator/Views/HistoryList.xaml
  src/Calculator/Views/HistoryList.xaml.cpp
  src/Calculator/Views/Memory.xaml
  src/Calculator/Views/Memory.xaml.cpp
  src/Calculator/Views/Memory.xaml.h
Labels: fixing approved issue

#498 Unit Converter - Calculate the rounding precision of results based on the source
  src/CalcManager/CalcManager.vcxproj
  src/CalcManager/CalcManager.vcxproj.filters
  src/CalcManager/NumberFormattingUtils.cpp
  src/CalcManager/NumberFormattingUtils.h
  src/CalcManager/UnitConverter.cpp
  src/CalcManager/UnitConverter.h
  src/CalcManager/pch.h
  src/CalculatorUnitTests/CalculatorManagerTest.cpp
  src/CalculatorUnitTests/UnitConverterTest.cpp
Labels: Enhancement, fixing approved issue

#572 Updated Calculator diagnostic data collection per the specification
  README.md
  src/CalcViewModel/ApplicationViewModel.cpp
  src/CalcViewModel/CalcViewModel.vcxproj
  src/CalcViewModel/Common/CalculatorButtonUser.h
  src/CalcViewModel/Common/CopyPasteManager.cpp
  src/CalcViewModel/Common/CopyPasteManager.h
  src/CalcViewModel/Common/TraceLogger.cpp
  src/CalcViewModel/Common/TraceLogger.h
  src/CalcViewModel/DataLoaders/CurrencyDataLoader.cpp
  src/CalcViewModel/DateCalculatorViewModel.cpp
  src/CalcViewModel/HistoryViewModel.cpp
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalcViewModel/StandardCalculatorViewModel.h
  src/CalcViewModel/UnitConverterViewModel.cpp
  src/CalcViewModel/UnitConverterViewModel.h
  src/Calculator/AboutFlyout.xaml
  src/Calculator/AboutFlyout.xaml.cpp
  src/Calculator/AboutFlyout.xaml.h
  src/Calculator/App.xaml.cpp
  src/Calculator/App.xaml.h
  src/Calculator/Calculator.vcxproj
  src/Calculator/Common/AppLifecycleLogger.cpp
  src/Calculator/Common/AppLifecycleLogger.h
  src/Calculator/Views/Calculator.xaml
  src/Calculator/Views/Calculator.xaml.cpp
  src/Calculator/Views/Calculator.xaml.h
  src/Calculator/Views/CalculatorProgrammerBitFlipPanel.xaml.cpp
  src/Calculator/Views/CalculatorProgrammerDisplayPanel.xaml
  src/Calculator/Views/CalculatorProgrammerDisplayPanel.xaml.cpp
  src/Calculator/Views/CalculatorProgrammerOperators.xaml.cpp
  src/Calculator/Views/CalculatorScientificAngleButtons.xaml.cpp
  src/Calculator/Views/DateCalculator.xaml
  src/Calculator/Views/DateCalculator.xaml.cpp
  src/Calculator/Views/DateCalculator.xaml.h
  src/Calculator/Views/MainPage.xaml.cpp
  src/Calculator/Views/UnitConverter.xaml
  src/Calculator/Views/UnitConverter.xaml.cpp
  src/Calculator/Views/UnitConverter.xaml.h
  src/Calculator/WindowFrameService.cpp
  src/Calculator/WindowFrameService.h
  src/CalculatorUnitTests/CopyPasteManagerTest.cpp
  src/CalculatorUnitTests/StandardViewModelUnitTests.cpp
  src/CalculatorUnitTests/UnitConverterViewModelUnitTests.cpp
Labels: Enhancement, fixing approved issue

#581 Add variable editing
  src/CalcViewModel/Common/Utils.h
  src/CalcViewModel/GraphingCalculator/GraphingCalculatorViewModel.cpp
  src/CalcViewModel/GraphingCalculator/GraphingCalculatorViewModel.h
  src/Calculator/App.xaml
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.cpp
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.h
  src/GraphControl/Control/Grapher.cpp
  src/GraphControl/Control/Grapher.h
  src/GraphingInterfaces/Common.h
  src/GraphingInterfaces/IGraph.h
Labels: Enhancement

#531 Modifying the title of the window to "Calculator [Dev]"
  src/Calculator/Views/TitleBar.xaml.cpp
Labels: fixing approved issue

#570 Fix #563: Odd dependency cycle
  src/CalcManager/CalculatorManager.cpp
  src/CalcManager/CalculatorManager.h
Labels: Codebase Quality, fixing approved issue

#603 Fixed issue where UI Responsive events were not fired
  src/CalcViewModel/ApplicationViewModel.cpp
  src/CalcViewModel/Common/TraceLogger.cpp
  src/CalcViewModel/Common/TraceLogger.h
  src/Calculator/Views/Calculator.xaml.cpp
  src/Calculator/Views/MainPage.xaml.cpp
Labels: fixing approved issue

#456 Restore user preferences
  src/CalcManager/UnitConverter.cpp
  src/CalcViewModel/UnitConverterViewModel.cpp
  src/CalcViewModel/UnitConverterViewModel.h
Labels: fixing approved issue

#579 Always-on-Top mode implemented
  docs/ManualTests.md
  src/CalcViewModel/ApplicationViewModel.cpp
  src/CalcViewModel/ApplicationViewModel.h
  src/CalcViewModel/Common/KeyboardShortcutManager.cpp
  src/CalcViewModel/Common/TraceLogger.cpp
  src/CalcViewModel/Common/TraceLogger.h
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalcViewModel/StandardCalculatorViewModel.h
  src/CalcViewModel/pch.h
  src/Calculator/App.xaml
  src/Calculator/App.xaml.cpp
  src/Calculator/Assets/CalcMDL2.ttf
  src/Calculator/Controls/OverflowTextBlock.cpp
  src/Calculator/Controls/OverflowTextBlock.h
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/Calculator.xaml
  src/Calculator/Views/Calculator.xaml.cpp
  src/Calculator/Views/Calculator.xaml.h
  src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml
  src/Calculator/Views/CalculatorScientificOperators.xaml
  src/Calculator/Views/CalculatorStandardOperators.xaml
  src/Calculator/Views/CalculatorStandardOperators.xaml.cpp
  src/Calculator/Views/CalculatorStandardOperators.xaml.h
  src/Calculator/Views/MainPage.xaml
  src/Calculator/Views/MainPage.xaml.cpp
  src/Calculator/Views/MainPage.xaml.h
  src/Calculator/Views/TitleBar.xaml
  src/Calculator/Views/TitleBar.xaml.cpp
  src/Calculator/Views/TitleBar.xaml.h
  src/Calculator/Views/UnitConverter.xaml
Labels: Enhancement, fixing approved issue
