Repository microsoft/calculator, pull requests merged in 2019-06, with the labels that each got.

#532 Update internal package version
  build/pipelines/templates/build-app-internal.yaml
  build/pipelines/templates/prepare-release-internalonly.yaml
Labels: tooling

#545 Drop __inline from conflicting declarations
  src/CalcManager/Ratpack/basex.cpp
  src/CalcManager/Ratpack/num.cpp
Labels: Codebase Quality

#542 Improving accessibility in scan mode
  src/Calculator/Controls/HorizontalNoOverflowStackPanel.cpp
Labels: Bug, fixing approved issue

#507 Bound the calendar picker to the control above
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/DateCalculator.xaml
Labels: Area: Accessibility, Bug, fixing approved issue

#553 Handle date difference for ends of months
  src/CalcViewModel/Common/DateCalculator.cpp
Labels: Bug

#501 Added Calculator Standard Mode UI Tests
  NOTICE.txt
  build/pipelines/templates/run-ui-tests.yaml
  src/Calculator.sln
  src/CalculatorUITestFramework/CalculatorUITestFramework.csproj
  src/CalculatorUITestFramework/HistoryPanel.cs
  src/CalculatorUITestFramework/MemoryPanel.cs
  src/CalculatorUITestFramework/NavigationMenu.cs
  src/CalculatorUITestFramework/NumberPad.cs
  src/CalculatorUITestFramework/StandardCalculatorPage.cs
  src/CalculatorUITestFramework/StandardOperatorsPanel.cs
  src/CalculatorUITestFramework/WinAppDriver.cs
  src/CalculatorUITestFramework/WindowsDriverExtensions.cs
  src/CalculatorUITestFramework/WindowsDriverLocalService.cs
  src/CalculatorUITestFramework/WindowsDriverServiceBuilder.cs
  src/CalculatorUITestFramework/WindowsElementExtensions.cs
  src/CalculatorUITests/CalculatorSession.cs
  src/CalculatorUITests/CalculatorUITests.csproj
  src/CalculatorUITests/ScenarioStandard.cs
  src/CalculatorUITests/StandardModeFunctionalTests.cs
Labels: Codebase Quality, fixing approved issue

#548 Update to v142 build tools for Visual Studio 2019
  build/pipelines/templates/build-app-internal.yaml
  build/pipelines/templates/build-app-public.yaml
  build/pipelines/templates/build-single-architecture.yaml
  build/pipelines/templates/package-appxbundle.yaml
  docs/Images/VSInstallationScreenshot.png
  src/CalcManager/CalcManager.vcxproj
  src/CalcViewModel/CalcViewModel.vcxproj
  src/CalcViewModel/Common/Utils.cpp
  src/Calculator.sln
  src/Calculator/App.xaml.cpp
  src/Calculator/Calculator.vcxproj
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj
Labels: build

#547 Create EquationTextBox control
  src/CalcViewModel/GraphingCalculator/EquationViewModel.cpp
  src/CalcViewModel/GraphingCalculator/EquationViewModel.h
  src/Calculator/App.xaml
  src/Calculator/Calculator.vcxproj
  src/Calculator/Calculator.vcxproj.filters
  src/Calculator/Controls/EquationTextBox.cpp
  src/Calculator/Controls/EquationTextBox.h
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Resources/es-ES/Resources.resw
  src/Calculator/Views/Calculator.xaml.h
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.cpp
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.h
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml
  src/GraphControl/Control/EquationCollection.h
  src/GraphControl/Control/Grapher.cpp
  src/GraphingInterfaces/IGraph.h
Labels: Enhancement

#558 Modify ClipTime to adjust the datetime to local time before clipping
  src/CalcViewModel/DateCalculatorViewModel.cpp
  src/CalcViewModel/DateCalculatorViewModel.h
Labels: Bug, fixing approved issue

#568 Update to SDK 18362
  src/CalcManager/CalcManager.vcxproj
  src/CalcViewModel/CalcViewModel.vcxproj
  src/Calculator/Calculator.vcxproj
  src/Calculator/Package.appxmanifest
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj
Labels: build

#566 Ensure consistent margins/padding with currency converter keypad
  src/Calculator/Views/UnitConverter.xaml
Labels: Bug, fixing approved issue
