Repository microsoft/calculator, pull requests merged in 2019-11, with the labels that each got.

#746 Remove AsyncHelper, Resource and Module.cpp from CalculatorUnitTests project.
  src/CalculatorUnitTests/AsyncHelper.cpp
  src/CalculatorUnitTests/AsyncHelper.h
  src/CalculatorUnitTests/CalculatorUnitTests.rc
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj.filters
  src/CalculatorUnitTests/Module.cpp
  src/CalculatorUnitTests/StandardViewModelUnitTests.cpp
  src/CalculatorUnitTests/pch.h
  src/CalculatorUnitTests/resource.h
Labels: codebase quality

#734 Add KeyboardAccelerators for AlwaysOnTop
  src/Calculator/Views/MainPage.xaml
  src/Calculator/Views/TitleBar.xaml
Labels: Enhancement, fixing approved issue

#689 Enable code analysis in the CalcManager project
  src/CalcManager/CalcManager.vcxproj
  src/CalcManager/CalculatorHistory.cpp
  src/CalcManager/CalculatorManager.h
  src/CalcManager/Ratpack/basex.cpp
  src/CalcManager/Ratpack/conv.cpp
  src/CalcManager/Ratpack/exp.cpp
  src/CalcManager/Ratpack/fact.cpp
  src/CalcManager/Ratpack/itrans.cpp
  src/CalcManager/Ratpack/itransh.cpp
  src/CalcManager/Ratpack/logic.cpp
  src/CalcManager/Ratpack/num.cpp
  src/CalcManager/Ratpack/rat.cpp
  src/CalcManager/Ratpack/ratpak.h
  src/CalcManager/Ratpack/support.cpp
  src/CalcManager/Ratpack/trans.cpp
  src/CalcManager/Ratpack/transh.cpp
Labels: codebase quality

#758 Replace wstring used in public methods by Platform::String in CalcViewModel
  src/CalcViewModel/ApplicationViewModel.cpp
  src/CalcViewModel/Common/AppResourceProvider.cpp
  src/CalcViewModel/Common/AppResourceProvider.h
  src/CalcViewModel/Common/CalculatorDisplay.cpp
  src/CalcViewModel/Common/CopyPasteManager.cpp
  src/CalcViewModel/Common/CopyPasteManager.h
  src/CalcViewModel/Common/KeyboardShortcutManager.cpp
  src/CalcViewModel/Common/LocalizationService.cpp
  src/CalcViewModel/Common/LocalizationService.h
  src/CalcViewModel/Common/LocalizationSettings.h
  src/CalcViewModel/Common/LocalizationStringUtil.h
  src/CalcViewModel/Common/NavCategory.cpp
  src/CalcViewModel/DataLoaders/CurrencyDataLoader.cpp
  src/CalcViewModel/DataLoaders/CurrencyDataLoader.h
  src/CalcViewModel/DataLoaders/UnitConverterDataLoader.cpp
  src/CalcViewModel/DateCalculatorViewModel.cpp
  src/CalcViewModel/HistoryViewModel.cpp
  src/CalcViewModel/HistoryViewModel.h
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalcViewModel/StandardCalculatorViewModel.h
  src/CalcViewModel/UnitConverterViewModel.cpp
  src/Calculator/AboutFlyout.xaml.cpp
  src/Calculator/Controls/CalculationResult.cpp
  src/Calculator/Controls/RadixButton.cpp
  src/Calculator/Converters/RadixToStringConverter.cpp
  src/Calculator/Views/Calculator.xaml.cpp
  src/Calculator/Views/Calculator.xaml.h
  src/Calculator/Views/CalculatorProgrammerBitFlipPanel.xaml.cpp
  src/Calculator/Views/CalculatorProgrammerOperators.xaml.cpp
  src/Calculator/Views/DateCalculator.xaml.cpp
  src/Calculator/Views/MainPage.xaml.cpp
  src/Calculator/Views/TitleBar.xaml.cpp
  src/Calculator/Views/UnitConverter.xaml.cpp
  src/CalculatorUnitTests/CopyPasteManagerTest.cpp
  src/CalculatorUnitTests/HistoryTests.cpp
Labels: fixing approved issue

#712 Modify how Calculator manages the visibility of the History button
  src/CalcViewModel/CalcViewModel.vcxproj
  src/CalcViewModel/CalcViewModel.vcxproj.filters
  src/CalcViewModel/Common/Utils.cpp
  src/CalcViewModel/ViewState.cpp
  src/CalcViewModel/ViewState.h
  src/Calculator/App.xaml.cpp
  src/Calculator/App.xaml.h
  src/Calculator/Views/Calculator.xaml
  src/Calculator/Views/Calculator.xaml.cpp
Labels: Bug, fixing approved issue

#773 Support high contrast for color picker and fix crashing bug
  src/Calculator/App.xaml
  src/Calculator/EquationStylePanelControl.xaml.cpp
  src/Calculator/EquationStylePanelControl.xaml.h
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.cpp
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.h
Labels: graphing calculator

#762 Make sure DateDifference::operator== compares DateTime::day
  src/CalcViewModel/Common/DateCalculator.h
Labels: codebase quality, fixing approved issue

#736 Fix the right arrow button of CalculationResult not disappearing in some cases
  src/Calculator/Controls/CalculationResult.cpp
  src/Calculator/Controls/CalculationResult.h
Labels: Bug, fixing approved issue

#769 Convert DateCalculatorViewModel to runtime class
  src/CalcViewModel/Common/DateCalculator.cpp
  src/CalcViewModel/Common/DateCalculator.h
  src/CalcViewModel/DateCalculatorViewModel.cpp
  src/CalcViewModel/DateCalculatorViewModel.h
  src/CalculatorUnitTests/DateCalculatorUnitTests.cpp
Labels: codebase quality, fixing approved issue

#752 Fully separate Calculator and CalcManager
  src/CalcViewModel/Common/Utils.h
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalcViewModel/StandardCalculatorViewModel.h
  src/Calculator/Views/Calculator.xaml.cpp
  src/Calculator/Views/Calculator.xaml.h
Labels: codebase quality, fixing approved issue

#786 Update build version to 1910
  build/pipelines/azure-pipelines.release.yaml
Labels: tooling

#790 Copyright headers
  src/GraphControl/Control/Equation.cpp
  src/GraphControl/Control/Equation.h
  src/GraphControl/Control/EquationCollection.h
  src/GraphControl/Control/Grapher.cpp
  src/GraphControl/Control/Grapher.h
  src/GraphControl/Control/InspectingDataSource.cpp
  src/GraphControl/Control/InspectingDataSource.h
  src/GraphControl/DirectX/ActiveTracingPointRenderer.cpp
  src/GraphControl/DirectX/ActiveTracingPointRenderer.h
  src/GraphControl/DirectX/DeviceResources.cpp
  src/GraphControl/DirectX/DeviceResources.h
  src/GraphControl/DirectX/DirectXHelper.h
  src/GraphControl/DirectX/NearestPointRenderer.cpp
  src/GraphControl/DirectX/NearestPointRenderer.h
  src/GraphControl/DirectX/RenderMain.cpp
  src/GraphControl/DirectX/RenderMain.h
  src/MockGraphingImpl/Mocks/MathSolver.cpp
  src/MockGraphingImpl/Mocks/MathSolver.h
  src/MockGraphingImpl/dllmain.cpp
Labels: graphing calculator

#750 force a call to m_expressionContainer->Measure in UpdateScrollButtons
  src/Calculator/Controls/OverflowTextBlock.cpp
  src/Calculator/Controls/OverflowTextBlock.h
Labels: Bug, fixing approved issue

#704 Key graph features
  src/CalcManager/CalcManager.vcxproj
  src/CalcViewModel/CalcViewModel.vcxproj
  src/CalcViewModel/CalcViewModel.vcxproj.filters
  src/CalcViewModel/GraphingCalculator/EquationViewModel.cpp
  src/CalcViewModel/GraphingCalculator/EquationViewModel.h
  src/CalcViewModel/GraphingCalculator/GraphingCalculatorViewModel.cpp
  src/CalcViewModel/GraphingCalculator/GraphingCalculatorViewModel.h
  src/CalcViewModel/GraphingCalculatorEnums.h
  src/Calculator/App.xaml
  src/Calculator/Calculator.vcxproj
  src/Calculator/Calculator.vcxproj.filters
  src/Calculator/Controls/EquationTextBox.cpp
  src/Calculator/Controls/EquationTextBox.h
  src/Calculator/Controls/MathRichEditBox.cpp
  src/Calculator/Controls/MathRichEditBox.h
  src/Calculator/Package.appxmanifest
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/TemplateSelectors/KeyGraphFeaturesTemplateSelector.cpp
  src/Calculator/TemplateSelectors/KeyGraphFeaturesTemplateSelector.h
  src/Calculator/Views/Calculator.xaml
  src/Calculator/Views/Calculator.xaml.h
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.cpp
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.h
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.cpp
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.h
  src/Calculator/Views/GraphingCalculator/KeyGraphFeaturesPanel.xaml
  src/Calculator/Views/GraphingCalculator/KeyGraphFeaturesPanel.xaml.cpp
  src/Calculator/Views/GraphingCalculator/KeyGraphFeaturesPanel.xaml.h
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj
  src/GraphControl/Control/Equation.cpp
  src/GraphControl/Control/Equation.h
  src/GraphControl/Control/EquationCollection.h
  src/GraphControl/Control/Grapher.cpp
  src/GraphControl/Control/Grapher.h
  src/GraphControl/GraphControl.vcxproj
  src/GraphControl/GraphControl.vcxproj.filters
  src/GraphingInterfaces/Common.h
  src/GraphingInterfaces/GraphingEnums.h
  src/GraphingInterfaces/IBitmap.h
  src/GraphingInterfaces/IGraph.h
  src/GraphingInterfaces/IGraphAnalyzer.h
  src/GraphingInterfaces/IGraphRenderer.h
  src/GraphingInterfaces/IMathSolver.h
  src/MockGraphingImpl/MockGraphingImpl.vcxproj
  src/MockGraphingImpl/MockGraphingImpl.vcxproj.filters
  src/MockGraphingImpl/Mocks/MathSolver.h
Labels: graphing calculator

#794 Run localization pipeline on the Hosted Windows 2019 pool
  build/pipelines/azure-pipelines.loc.yaml
Labels: tooling

#787 Fix focus for EquationTextBox
  src/Calculator/Controls/EquationTextBox.cpp
  src/Calculator/Controls/EquationTextBox.h
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.cpp
Labels: graphing calculator

#766 Convert CopyPasteManager to runtime class
  src/CalcViewModel/CalcViewModel.vcxproj
  src/CalcViewModel/CalcViewModel.vcxproj.filters
  src/CalcViewModel/Common/CopyPasteManager.cpp
  src/CalcViewModel/Common/CopyPasteManager.h
  src/CalcViewModel/Common/NumberBase.h
  src/CalcViewModel/Common/Utils.cpp
  src/CalcViewModel/Common/Utils.h
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalcViewModel/StandardCalculatorViewModel.h
  src/CalcViewModel/UnitConverterViewModel.cpp
  src/CalcViewModel/pch.h
  src/Calculator/Views/UnitConverter.xaml.cpp
  src/CalculatorUnitTests/CopyPasteManagerTest.cpp
  src/CalculatorUnitTests/Helpers.h
  src/CalculatorUnitTests/StandardViewModelUnitTests.cpp
Labels: codebase quality, fixing approved issue

#782 Update share output
  src/CalcViewModel/Common/Utils.cpp
  src/CalcViewModel/Common/Utils.h
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.cpp
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.h
  src/GraphControl/Control/Grapher.cpp
  src/GraphControl/Control/Grapher.h
Labels: graphing calculator

#793 Update styles for buttons on Graph and ListView
  src/Calculator/App.xaml
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.cpp
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml
Labels: graphing calculator

#791 Refactor Equation to be treated as a model and update Key Graph Features
  src/CalcViewModel/CalcViewModel.vcxproj
  src/CalcViewModel/GraphingCalculator/EquationViewModel.cpp
  src/CalcViewModel/GraphingCalculator/EquationViewModel.h
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.cpp
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.h
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.cpp
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.h
  src/GraphControl/Control/Equation.cpp
  src/GraphControl/Control/Equation.h
  src/GraphControl/Control/Grapher.cpp
  src/GraphControl/Control/Grapher.h
  src/GraphControl/Control/InspectingDataSource.cpp
  src/GraphControl/Control/InspectingDataSource.h
  src/GraphControl/GraphControl.vcxproj
  src/GraphControl/GraphControl.vcxproj.filters
Labels: graphing calculator

#804 Equation button updates: Enable/Disable on click, button content f1, f2, f3..., visibility icon on hover
  src/CalcViewModel/CalcViewModel.vcxproj
  src/CalcViewModel/GraphingCalculator/EquationViewModel.cpp
  src/CalcViewModel/GraphingCalculator/EquationViewModel.h
  src/Calculator/App.xaml
  src/Calculator/Calculator.vcxproj.filters
  src/Calculator/Controls/EquationTextBox.cpp
  src/Calculator/Controls/EquationTextBox.h
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.cpp
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.h
  src/Calculator/Views/GraphingCalculator/KeyGraphFeaturesPanel.xaml
  src/Calculator/Views/GraphingCalculator/KeyGraphFeaturesPanel.xaml.cpp
  src/Calculator/Views/GraphingCalculator/KeyGraphFeaturesPanel.xaml.h
  src/GraphControl/Control/Equation.cpp
  src/GraphControl/Control/Equation.h
  src/GraphControl/Control/EquationCollection.h
  src/GraphControl/Control/Grapher.cpp
  src/GraphControl/Control/Grapher.h
  src/MockGraphingImpl/MockGraphingImpl.vcxproj
Labels: graphing calculator

#812 Changing CalculatorManager::GetSavedCommands to return a const ref
  src/CalcManager/CalculatorManager.h
Labels: codebase quality, triage needed

#803 Added support for small windows in the graphing calculator
  src/CalcViewModel/Common/Automation/NarratorAnnouncement.cpp
  src/CalcViewModel/Common/Automation/NarratorAnnouncement.h
  src/Calculator/Calculator.vcxproj.filters
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.cpp
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.h
  src/Calculator/Views/MainPage.xaml
Labels: graphing calculator

#822 Add tooltips to buttons in graphing calculator
  src/Calculator/App.xaml
  src/Calculator/Calculator.vcxproj.filters
  src/Calculator/Controls/EquationTextBox.cpp
  src/Calculator/Controls/EquationTextBox.h
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.cpp
  src/Calculator/Views/GraphingCalculator/KeyGraphFeaturesPanel.xaml
Labels: graphing calculator
