Repository microsoft/calculator, pull requests merged in 2019-04, with the labels that each got.

#365 Update README to add description of "date calculation" functionality
  README.md
Labels: Documentation

#374 Add Reveal Highlight on AccentCalcButtonStyle + fix accessibility iss…
  src/Calculator/App.xaml
Labels: Bug

#217 Optimize and simplify CalculationResult to be able to update the FontSize and the DisplayMargin without fully updating the Style.
  src/Calculator/App.xaml
  src/Calculator/Controls/CalculationResult.cpp
  src/Calculator/Controls/CalculationResult.h
  src/Calculator/Views/Calculator.xaml
  src/Calculator/Views/Calculator.xaml.cpp
  src/Calculator/Views/Calculator.xaml.h
  src/Calculator/Views/UnitConverter.xaml
Labels: Codebase Quality

#298 Fix invalid check of m_precedenceOpCount
  src/CalcManager/CEngine/scicomm.cpp
  src/CalcManager/Header Files/CalcEngine.h
Labels: Bug, Fixing Approved Issue

#391 Prevent the application to crash when the current page is Date Calculation and users paste a text
  src/CalcViewModel/ApplicationViewModel.cpp
Labels: Bug, Fixing Approved Issue, Waiting For Update

#369 Keep input when users refresh currency rates
  src/CalcManager/UnitConverter.cpp
  src/CalcManager/UnitConverter.h
  src/CalcViewModel/UnitConverterViewModel.cpp
  src/CalcViewModel/UnitConverterViewModel.h
  src/CalculatorUnitTests/UnitConverterViewModelUnitTests.h
Labels: Bug, Fixing Approved Issue

#412 Modify how modulo is calculated in Normal and Scientific mode.
  src/CalcManager/CEngine/Rational.cpp
  src/CalcManager/CEngine/RationalMath.cpp
  src/CalcManager/CEngine/scioper.cpp
  src/CalcManager/Header Files/CalcEngine.h
  src/CalcManager/Header Files/RationalMath.h
  src/CalcManager/Ratpack/exp.cpp
  src/CalcManager/Ratpack/fact.cpp
  src/CalcManager/Ratpack/itrans.cpp
  src/CalcManager/Ratpack/logic.cpp
  src/CalcManager/Ratpack/ratpak.h
  src/CalcManager/Ratpack/support.cpp
  src/CalculatorUnitTests/CalcEngineTests.cpp
  src/CalculatorUnitTests/CalcInputTest.cpp
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj.filters
  src/CalculatorUnitTests/RationalTest.cpp
Labels: Bug, Fixing Approved Issue

#440 Fix #407: Removed AppBar, OperatorTextBox and OperandTextBox controls
  src/CalcViewModel/ApplicationViewModel.cpp
  src/CalcViewModel/ApplicationViewModel.h
  src/CalcViewModel/StandardCalculatorViewModel.h
  src/Calculator/Calculator.vcxproj
  src/Calculator/Calculator.vcxproj.filters
  src/Calculator/Controls/AppBar.h
  src/Calculator/Controls/OperandTextBox.cpp
  src/Calculator/Controls/OperandTextBox.h
  src/Calculator/Controls/OperatorTextBox.cpp
  src/Calculator/Controls/OperatorTextBox.h
  src/Calculator/Views/Calculator.xaml
  src/Calculator/Views/MainPage.xaml.cpp
  src/Calculator/Views/MainPage.xaml.h
  src/Calculator/Views/SupplementaryResults.xaml.h
Labels: Fixing Approved Issue

#444 Add support for Pyeong, a Korean floorspace unit.
  src/CalcManager/UnitConverter.cpp
  src/CalcViewModel/DataLoaders/UnitConverterDataConstants.h
  src/CalcViewModel/DataLoaders/UnitConverterDataLoader.cpp
  src/Calculator/Resources/en-US/Resources.resw
Labels: Fixing Approved Issue

#403 Decrease CPU usage of OverflowTextBlock + optimization
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalcViewModel/StandardCalculatorViewModel.h
  src/Calculator/Calculator.vcxproj
  src/Calculator/Calculator.vcxproj.filters
  src/Calculator/Controls/OverflowTextBlock.cpp
  src/Calculator/Controls/OverflowTextBlock.h
  src/Calculator/Converters/ExpressionItemContainerStyle.cpp
  src/Calculator/Converters/ExpressionItemContainerStyle.h
  src/Calculator/Views/Calculator.xaml
  src/Calculator/Views/Calculator.xaml.cpp
  src/Calculator/Views/Calculator.xaml.h
Labels: Bug, Fixing Approved Issue

#433 Refactored XAML x:Names
  src/Calculator/App.xaml
  src/Calculator/Controls/CalculationResult.cpp
  src/Calculator/Controls/OverflowTextBlock.cpp
  src/Calculator/Views/Calculator.xaml
  src/Calculator/Views/Calculator.xaml.cpp
  src/Calculator/Views/CalculatorProgrammerDisplayPanel.xaml
  src/Calculator/Views/CalculatorProgrammerDisplayPanel.xaml.cpp
  src/Calculator/Views/CalculatorProgrammerOperators.xaml
  src/Calculator/Views/CalculatorProgrammerOperators.xaml.cpp
  src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml
  src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml.cpp
  src/Calculator/Views/CalculatorScientificAngleButtons.xaml
  src/Calculator/Views/CalculatorScientificAngleButtons.xaml.cpp
  src/Calculator/Views/CalculatorScientificOperators.xaml
  src/Calculator/Views/CalculatorScientificOperators.xaml.cpp
  src/Calculator/Views/CalculatorStandardOperators.xaml
  src/Calculator/Views/HistoryList.xaml
  src/Calculator/Views/MainPage.xaml
  src/Calculator/Views/NumberPad.xaml
  src/Calculator/Views/NumberPad.xaml.cpp
  src/Calculator/Views/UnitConverter.xaml
  src/Calculator/Views/UnitConverter.xaml.cpp
Labels: Codebase Quality, Waiting For Update

#465 Fix test code that never executes
  src/CalculatorUnitTests/UnitConverterViewModelUnitTests.cpp
Labels: Codebase Quality, Fixing Approved Issue

#410 Fix #409 and #59 - UI issues with UnitConverter in RtL
  src/Calculator/Views/UnitConverter.xaml
  src/Calculator/Views/UnitConverter.xaml.cpp
  src/Calculator/Views/UnitConverter.xaml.h
Labels: Bug, Fixing Approved Issue

#442 Make it obvious that the window doesn't have focus + simplify how the app manages the title bar.
  src/Calculator/App.xaml
  src/Calculator/App.xaml.cpp
  src/Calculator/Calculator.vcxproj
  src/Calculator/Calculator.vcxproj.filters
  src/Calculator/Common/TitleBarHelper.cpp
  src/Calculator/Common/TitleBarHelper.h
  src/Calculator/Views/Calculator.xaml
  src/Calculator/Views/HistoryList.xaml
  src/Calculator/Views/HistoryList.xaml.cpp
  src/Calculator/Views/HistoryList.xaml.h
  src/Calculator/Views/MainPage.xaml
  src/Calculator/Views/MainPage.xaml.cpp
  src/Calculator/Views/MainPage.xaml.h
  src/Calculator/Views/Memory.xaml
  src/Calculator/Views/Memory.xaml.cpp
  src/Calculator/Views/Memory.xaml.h
  src/Calculator/Views/TitleBar.xaml
  src/Calculator/Views/TitleBar.xaml.cpp
  src/Calculator/Views/TitleBar.xaml.h
Labels: Fixing Approved Issue

#447 Clicking on the same element in the hamburger view should re-open that view, like the menu items do
  src/Calculator/Views/MainPage.xaml
  src/Calculator/Views/MainPage.xaml.cpp
  src/Calculator/Views/MainPage.xaml.h
Labels: Fixing Approved Issue

#458 Add Pan/Zoom support for the graph surface
  src/GraphControl/Control/Grapher.cpp
  src/GraphControl/Control/Grapher.h
  src/GraphingInterfaces/GraphingEnums.h
  src/GraphingInterfaces/IGraphRenderer.h
Labels: Enhancement, Fixing Approved Issue

#390 Updates to copypastemanager
  src/CalcViewModel/Common/CopyPasteManager.cpp
  src/CalcViewModel/Common/CopyPasteManager.h
Labels: Codebase Quality, Fixing Approved Issue

#470 Update README to include infinite precision
  README.md
  docs/ApplicationArchitecture.md
Labels: Documentation

#345 Fix bug when the negate sign is before a space
  src/CalcViewModel/StandardCalculatorViewModel.cpp
Labels: Bug, Fixing Approved Issue
