Repository microsoft/calculator, pull requests merged in 2019-03, with the labels that each got.

#225 add .editorconfig to set some basic coding styles
  src/.editorconfig
  src/Calculator.sln
Labels: No Behavior Change, Tooling

#230 fix: redundant semicolons
  src/CalcManager/UnitConverter.cpp
  src/Calculator/Views/DateCalculator.xaml.cpp
  src/CalculatorUnitTests/CopyPasteManagerTest.cpp
Labels: No Behavior Change

#239 Remove end-of-line from .editorconfig
  src/.editorconfig
Labels: No Behavior Change

#257 Remove duplicate .editorconfig.
  .editorconfig
  src/.editorconfig
Labels: No Behavior Change

#269 CopyPasteManagerTest fails to test all values
  src/CalculatorUnitTests/CopyPasteManagerTest.cpp
Labels: No Behavior Change

#235 Eliminate redundant copies of EMPTY_UNIT object, saving 2.5 KB.
  src/CalcManager/UnitConverter.h
Labels: No Behavior Change

#234 Make 73 numeric constants actually const, moving them into the .rdata section
  src/CalcManager/Ratpack/conv.cpp
  src/CalcManager/Ratpack/ratconst.h
  src/CalcManager/Ratpack/ratpak.h
  src/CalcManager/Ratpack/support.cpp
Labels: No Behavior Change

#186 Fix declarations of functions
  src/CalcManager/CEngine/CalcUtils.cpp
  src/CalcManager/CEngine/History.cpp
  src/CalcManager/CEngine/scicomm.cpp
  src/CalcManager/CalcException.h
  src/CalcManager/CalcManager.vcxproj.filters
  src/CalcViewModel/Common/AppResourceProvider.cpp
  src/CalcViewModel/Common/TraceLogger.cpp
  src/CalculatorUnitTests/Mocks/CurrencyHttpClient.cpp
Labels: No Behavior Change

#247 Remove rendertransform never used
  src/Calculator/Views/UnitConverter.xaml
Labels: No Behavior Change

#284 Fixes #282 Narrator does not convey error information when no more Right Parenthesis can be added in expression.
  src/CalcManager/CEngine/scicomm.cpp
  src/CalcManager/CalculatorManager.cpp
  src/CalcManager/CalculatorManager.h
  src/CalcManager/Header Files/ICalcDisplay.h
  src/CalcViewModel/Common/Automation/NarratorAnnouncement.cpp
  src/CalcViewModel/Common/Automation/NarratorAnnouncement.h
  src/CalcViewModel/Common/CalculatorDisplay.cpp
  src/CalcViewModel/Common/CalculatorDisplay.h
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalcViewModel/StandardCalculatorViewModel.h
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml
  src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml.cpp
  src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml.h
  src/Calculator/Views/CalculatorScientificOperators.xaml
  src/Calculator/Views/CalculatorScientificOperators.xaml.cpp
  src/Calculator/Views/CalculatorScientificOperators.xaml.h
  src/CalculatorUnitTests/CalculatorManagerTest.cpp
Labels: Behavior Change, Fixing Approved Issue

#208 Replace custom ARRAYSIZE macro with std::size
  src/CalcManager/CEngine/scicomm.cpp
  src/CalcManager/CEngine/sciset.cpp
  src/CalcManager/pch.h
  src/CalcViewModel/Common/CopyPasteManager.cpp
  src/CalcViewModel/Common/LocalizationSettings.h
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalcViewModel/pch.h
Labels: No Behavior Change

#213 Activate TextSelection on all interesting values/results
  src/Calculator/App.xaml
  src/Calculator/Views/DateCalculator.xaml
  src/Calculator/Views/HistoryList.xaml
  src/Calculator/Views/MemoryListItem.xaml
Labels: Behavior Change, Fixing Approved Issue

#279 Fix Grid.Row value
  src/Calculator/Views/NumberPad.xaml
Labels: Behavior Change

#195 DateDiff: Optimize how we build the string used when we calculate the difference between 2 dates
  src/CalcViewModel/DateCalculatorViewModel.cpp
  src/CalcViewModel/DateCalculatorViewModel.h
  src/CalculatorUnitTests/DateCalculatorUnitTests.cpp
Labels: No Behavior Change

#176 Added support for pasting of monetary values
  src/CalcViewModel/Common/CopyPasteManager.cpp
  src/CalcViewModel/Common/CopyPasteManager.h
  src/CalcViewModel/Common/Utils.cpp
  src/CalcViewModel/Common/Utils.h
  src/CalculatorUnitTests/CopyPasteManagerTest.cpp
Labels: Behavior Change, Fixing Approved Issue

#200 Improving code style : verbosity, indentation levels
  src/CalcManager/CEngine/History.cpp
  src/CalcManager/CalculatorManager.cpp
  src/CalcManager/UnitConverter.cpp
Labels: No Behavior Change

#241 Propose minor code-cleanups
  src/CalcViewModel/UnitConverterViewModel.cpp
Labels: No Behavior Change

#323 Add explicit [[fallthrough]] attribute in Ratpack
  src/CalcManager/Ratpack/conv.cpp
Labels: Codebase Quality, No Behavior Change

#242 Fix formatting issues with CurrencyConverter and some locales
  src/CalcViewModel/UnitConverterViewModel.cpp
Labels: Behavior Change, Fixing Approved Issue

#327 Hide the history button when in Programmer mode
  src/Calculator/Views/Calculator.xaml
  src/Calculator/Views/Calculator.xaml.cpp
Labels: Behavior Change, Fixing Approved Issue

#246 Fix auto-scaling of CalculationResult when the current locale displays currency symbols on the right
  src/Calculator/Views/UnitConverter.xaml
  src/Calculator/Views/UnitConverter.xaml.cpp
Labels: Behavior Change, Fixing Approved Issue

#330 Remove unused member field from CalculatorHistory
  src/CalcManager/CalculatorHistory.cpp
  src/CalcManager/CalculatorHistory.h
  src/CalcManager/CalculatorManager.cpp
  src/CalculatorUnitTests/CalcEngineTests.cpp
Labels: Codebase Quality, No Behavior Change

#334 Replace fallthrough comment with C++17's attribute
  src/CalcManager/CalculatorManager.cpp
Labels: Codebase Quality, No Behavior Change

#329 Remove redundant type qualifiers on function return type
  src/CalcManager/CalculatorManager.h
Labels: Codebase Quality, No Behavior Change

#253 Propose code-cleanups#2
  src/CalcManager/CalculatorHistory.cpp
  src/CalcManager/CalculatorManager.cpp
Labels: No Behavior Change

#332 Fix order of initialization list in CalculatorManager ctor
  src/CalcManager/CalculatorManager.cpp
  src/CalcManager/ExpressionCommand.cpp
Labels: Codebase Quality, No Behavior Change

#360 [Build] Remove conditional inclusion of resw files
  src/Calculator/Calculator.vcxproj
Labels: Build

#363 Disable use of min/max macros defined by Windows headers.
  src/CalcManager/Ratpack/conv.cpp
  src/CalcManager/Ratpack/logic.cpp
  src/CalcManager/Ratpack/ratpak.h
  src/CalcManager/pch.h
  src/CalcViewModel/pch.h
  src/Calculator/Controls/CalculationResult.cpp
  src/Calculator/pch.h
  src/CalculatorUnitTests/pch.h
Labels: Codebase Quality, No Behavior Change

#346 Accept plus/minus sign before a parenthesis in ClipboardManager
  src/CalcViewModel/Common/CopyPasteManager.cpp
  src/CalculatorUnitTests/CopyPasteManagerTest.cpp
Labels: Bug, Fixing Approved Issue

#381 [Build] Don't run component governance detection in postbuild steps
  build/pipelines/templates/package-appxbundle.yaml
  build/pipelines/templates/prepare-release-internalonly.yaml
  build/pipelines/templates/run-unit-tests.yaml
Labels: Tooling

#373 Fix padding of unit converter when the locale displays currency symbols on the left
  src/Calculator/Views/UnitConverter.xaml
Labels: Bug, Fixing Approved Issue

#249 Improve performance of SupplementaryResult + Modify the height of RowDltrUnits when UnitConverter is in Landscape
  src/Calculator/Calculator.vcxproj
  src/Calculator/Calculator.vcxproj.filters
  src/Calculator/Controls/HorizontalNoOverflowStackPanel.cpp
  src/Calculator/Controls/HorizontalNoOverflowStackPanel.h
  src/Calculator/Controls/SupplementaryItemsControl.cpp
  src/Calculator/Views/SupplementaryResults.xaml
  src/Calculator/Views/SupplementaryResults.xaml.cpp
  src/Calculator/Views/SupplementaryResults.xaml.h
  src/Calculator/Views/UnitConverter.xaml
  src/Calculator/Views/UnitConverter.xaml.cpp
  src/Calculator/Views/UnitConverter.xaml.h
Labels: Bug, Fixing Approved Issue

#212 Replace custom types with standard ones
  src/CalcManager/CEngine/CalcInput.cpp
  src/CalcManager/CEngine/CalcUtils.cpp
  src/CalcManager/CEngine/History.cpp
  src/CalcManager/CEngine/Number.cpp
  src/CalcManager/CEngine/Rational.cpp
  src/CalcManager/CEngine/RationalMath.cpp
  src/CalcManager/CEngine/calc.cpp
  src/CalcManager/CEngine/scicomm.cpp
  src/CalcManager/CEngine/scidisp.cpp
  src/CalcManager/CEngine/scifunc.cpp
  src/CalcManager/CEngine/scioper.cpp
  src/CalcManager/CEngine/sciset.cpp
  src/CalcManager/CalculatorManager.cpp
  src/CalcManager/CalculatorVector.h
  src/CalcManager/Header Files/CalcEngine.h
  src/CalcManager/Header Files/CalcInput.h
  src/CalcManager/Header Files/CalcUtils.h
  src/CalcManager/Ratpack/CalcErr.h
  src/CalcManager/Ratpack/basex.cpp
  src/CalcManager/Ratpack/conv.cpp
  src/CalcManager/Ratpack/exp.cpp
  src/CalcManager/Ratpack/fact.cpp
  src/CalcManager/Ratpack/itrans.cpp
  src/CalcManager/Ratpack/logic.cpp
  src/CalcManager/Ratpack/num.cpp
  src/CalcManager/Ratpack/ratconst.h
  src/CalcManager/Ratpack/ratpak.h
  src/CalcManager/Ratpack/support.cpp
  src/CalcManager/Ratpack/trans.cpp
  src/CalcManager/Ratpack/transh.cpp
  src/CalcManager/pch.h
  src/CalcViewModel/Common/DateCalculator.h
Labels: Codebase Quality
