Repository microsoft/calculator, pull requests merged in 2019-09, with the labels that each got.

#657 Update documentation for communicating discovered security vulnerabilities
  README.md
  SECURITY.md
Labels: documentation

#647 Replace AppChromeAcrylicHostBackdropMediumLowBrush from OverflowTextBlock + improvements
  src/Calculator/Controls/OverflowTextBlock.cpp
  src/Calculator/Controls/OverflowTextBlock.h
  src/Calculator/Views/Calculator.xaml
Labels: Codebase Quality, fixing approved issue

#652 Fix scroll buttons in CalculationResult
  src/Calculator/Controls/CalculationResult.cpp
  src/Calculator/Controls/CalculationResult.h
Labels: Bug, fixing approved issue

#628 Add copy button to history menu item context menu
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/HistoryList.xaml
  src/Calculator/Views/HistoryList.xaml.cpp
  src/Calculator/Views/HistoryList.xaml.h
Labels: fixing approved issue

#679 Disable ProgrammerRadixOperators when not visible
  src/Calculator/Views/OperatorsPanel.xaml
Labels: Bug, fixing approved issue

#676 Prevent the history panel to be displayed when using the Programmer mode
  src/Calculator/Views/Calculator.xaml.cpp
Labels: Bug, fixing approved issue

#672 Switch to RichEdit math mode in EquationTextBox
  src/CalcManager/CalcManager.vcxproj
  src/CalcViewModel/CalcViewModel.vcxproj
  src/Calculator/App.xaml
  src/Calculator/Calculator.vcxproj
  src/Calculator/Controls/EquationTextBox.cpp
  src/Calculator/Controls/EquationTextBox.h
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.cpp
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.h
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj
  src/CalculatorUnitTests/NavCategoryUnitTests.cpp
  src/GraphControl/Control/Equation.cpp
  src/GraphControl/Control/Grapher.cpp
  src/GraphControl/GraphControl.vcxproj
  src/MockGraphingImpl/MockGraphingImpl.vcxproj
Labels: Enhancement, fixing approved issue, graphing calculator

#668 Update color picker
  src/CalcViewModel/CalcViewModel.vcxproj.filters
  src/CalcViewModel/GraphingCalculator/EquationViewModel.cpp
  src/CalcViewModel/GraphingCalculator/EquationViewModel.h
  src/Calculator/App.xaml
  src/Calculator/Calculator.vcxproj
  src/Calculator/Calculator.vcxproj.filters
  src/Calculator/Controls/EquationTextBox.cpp
  src/Calculator/Controls/EquationTextBox.h
  src/Calculator/EquationStylePanelControl.xaml
  src/Calculator/EquationStylePanelControl.xaml.cpp
  src/Calculator/EquationStylePanelControl.xaml.h
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.cpp
  src/Calculator/Views/GraphingCalculator/EquationInputArea.xaml.h
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.cpp
  src/GraphControl/Control/Equation.cpp
  src/GraphControl/Control/Equation.h
  src/GraphControl/Control/EquationCollection.h
  src/GraphControl/Control/Grapher.cpp
  src/GraphControl/Control/Grapher.h
Labels: Enhancement, fixing approved issue, graphing calculator

#619 Do not collapse Update Rates button in a transient state
  src/Calculator/Views/UnitConverter.xaml
  src/Calculator/Views/UnitConverter.xaml.cpp
Labels: fixing approved issue

#681 Update unit test signature
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj
Labels: build

#675 Modify how narrator names the first and last bits of a number in Bit Flip
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/CalculatorProgrammerBitFlipPanel.xaml.cpp
  src/Calculator/Views/CalculatorProgrammerBitFlipPanel.xaml.h
Labels: Bug, fixing approved issue

#646 Code cleanup: simplify NarratorNotifier
  src/CalcViewModel/CalcViewModel.vcxproj
  src/CalcViewModel/CalcViewModel.vcxproj.filters
  src/CalcViewModel/Common/Automation/INarratorAnnouncementHost.h
  src/CalcViewModel/Common/Automation/LiveRegionHost.cpp
  src/CalcViewModel/Common/Automation/LiveRegionHost.h
  src/CalcViewModel/Common/Automation/NarratorAnnouncement.cpp
  src/CalcViewModel/Common/Automation/NarratorAnnouncement.h
  src/CalcViewModel/Common/Automation/NarratorAnnouncementHostFactory.cpp
  src/CalcViewModel/Common/Automation/NarratorAnnouncementHostFactory.h
  src/CalcViewModel/Common/Automation/NarratorNotifier.cpp
  src/CalcViewModel/Common/Automation/NarratorNotifier.h
  src/CalcViewModel/Common/Automation/NotificationHost.cpp
  src/CalcViewModel/Common/Automation/NotificationHost.h
  src/Calculator/Converters/BooleanToVisibilityConverter.cpp
  src/Calculator/pch.h
Labels: Codebase Quality

#662 Update Calc Engine for new functions needed for keyboard refresh
  src/CalcManager/CEngine/CalcInput.cpp
  src/CalcManager/CEngine/CalcUtils.cpp
  src/CalcManager/CEngine/History.cpp
  src/CalcManager/CEngine/scicomm.cpp
  src/CalcManager/CEngine/scifunc.cpp
  src/CalcManager/CEngine/scioper.cpp
  src/CalcManager/CalculatorManager.cpp
  src/CalcManager/CalculatorManager.h
  src/CalcManager/Command.h
  src/CalcManager/Header Files/CCommand.h
  src/CalcManager/Header Files/CalcEngine.h
  src/CalcManager/Header Files/CalcInput.h
  src/CalcManager/Header Files/EngineStrings.h
  src/CalcManager/Header Files/History.h
  src/CalcManager/Header Files/ICalcDisplay.h
  src/CalcManager/pch.h
  src/CalcViewModel/Common/CalculatorDisplay.cpp
  src/CalcViewModel/Common/CalculatorDisplay.h
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalcViewModel/StandardCalculatorViewModel.h
  src/Calculator/Resources/en-US/CEngineStrings.resw
  src/CalculatorUnitTests/CalculatorManagerTest.cpp
Labels: Enhancement, fixing approved issue
