Repository microsoft/calculator, pull requests merged in 2019-05, with the labels that each got.

#484 Update to Windows UI Library 2.1
  internal/Calculator.TestPackage/Calculator.TestPackage.csproj
  src/Calculator/Calculator.vcxproj
  src/Calculator/packages.config
Labels: fixing approved issue

#270 Accept exponential numbers without -/+ sign.
  src/CalcViewModel/Common/CopyPasteManager.cpp
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalculatorUnitTests/CopyPasteManagerTest.cpp
  src/CalculatorUnitTests/StandardViewModelUnitTests.cpp
Labels: Bug, fixing approved issue

#392 Remove Serialize/Deserialize functions never used in StandardCalculatorViewModel, UnitConverter, UnitConverterViewModel and CalculatorManager
  src/CalcManager/CalculatorManager.cpp
  src/CalcManager/CalculatorManager.h
  src/CalcManager/UnitConverter.cpp
  src/CalcManager/UnitConverter.h
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalcViewModel/StandardCalculatorViewModel.h
  src/CalcViewModel/UnitConverterViewModel.cpp
  src/CalcViewModel/UnitConverterViewModel.h
  src/CalculatorUnitTests/CalculatorManagerTest.cpp
  src/CalculatorUnitTests/StandardViewModelUnitTests.cpp
  src/CalculatorUnitTests/UnitConverterTest.cpp
  src/CalculatorUnitTests/UnitConverterViewModelUnitTests.cpp
  src/CalculatorUnitTests/UnitConverterViewModelUnitTests.h
Labels: Codebase Quality, fixing approved issue

#430 Keep spaces when users copy an error message
  src/CalcViewModel/StandardCalculatorViewModel.cpp
Labels: Bug, fixing approved issue

#499 Taskbar and start menu jumplist items should not be pinnable/unpinnable or removable
  src/Calculator/App.xaml.cpp
Labels: Bug, fixing approved issue

#289 Fix unit tests to run on non-english devices
  src/CalcViewModel/Common/LocalizationService.cpp
  src/CalcViewModel/Common/LocalizationService.h
  src/CalcViewModel/Common/LocalizationSettings.h
  src/CalcViewModel/DataLoaders/CurrencyDataLoader.cpp
  src/CalcViewModel/DataLoaders/CurrencyDataLoader.h
  src/CalcViewModel/DateCalculatorViewModel.cpp
  src/CalcViewModel/UnitConverterViewModel.cpp
  src/Calculator/Views/Calculator.xaml.cpp
  src/Calculator/Views/DateCalculator.xaml.cpp
  src/CalculatorUnitTests/CurrencyConverterUnitTests.cpp
  src/CalculatorUnitTests/UnitTestApp.xaml.cpp
Labels: Tooling, fixing approved issue

#506 Removed entrance transition for about button in NavigationView
  src/Calculator/Views/MainPage.xaml
Labels: Area: User Experience, Bug, fixing approved issue

#509 Updating terminology in new feature development process for clarity
  docs/NewFeatureProcess.md
Labels: Documentation

#503 Added the name property for right/left scroll buttons on screen
  src/Calculator/App.xaml
  src/Calculator/Resources/en-US/Resources.resw
Labels: Area: Accessibility, Bug, fixing approved issue

#510 Update bug/feature templates to track if submitter requests assignment
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation

#516 Make the solution compilable on systems in Chinese
  src/CalcManager/CalcManager.vcxproj
  src/CalcViewModel/CalcViewModel.vcxproj
  src/Calculator/Calculator.vcxproj
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj
Labels: Bug, fixing approved issue
