Repository microsoft/calculator, pull requests merged in 2019-08, with the labels that each got.

#256 Currency rate: always display minimum 4 significant decimals or 2 trailing zeros if the number is integer
  src/CalcViewModel/DataLoaders/CurrencyDataLoader.cpp
  src/CalcViewModel/DataLoaders/CurrencyDataLoader.h
  src/CalculatorUnitTests/CurrencyConverterUnitTests.cpp
Labels: fixing approved issue

#624 Updated README to note the requirement for installing WinAppDriver
  README.md
Labels: documentation

#627 Prevent Dev title from showing up on Store builds
  src/Calculator/Calculator.vcxproj
  src/Calculator/Views/TitleBar.xaml.cpp
Labels: Bug

#601 Adding share functionality to Graphing Calculator
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.cpp
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.h
  src/GraphControl/Control/Grapher.cpp
  src/GraphControl/Control/Grapher.h
  src/GraphingInterfaces/IBitmap.h
  src/GraphingInterfaces/IGraphRenderer.h
Labels: graphing calculator

#637 Adds zoom buttons to graph controls
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.cpp
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.h
  src/GraphControl/Control/Grapher.cpp
  src/GraphControl/Control/Grapher.h
Labels: graphing calculator

#632 Fix regression bug with application title no longer grayed out.
  src/Calculator/Views/TitleBar.xaml
Labels: fixing approved issue

#623 Remove unused expression item template selector
  src/Calculator/Views/Calculator.xaml
Labels: Codebase Quality

#634 General improvement of the title bar for Always-On-Top.
  src/CalcViewModel/ApplicationViewModel.h
  src/Calculator/Views/MainPage.xaml
  src/Calculator/Views/MainPage.xaml.cpp
  src/Calculator/Views/MainPage.xaml.h
  src/Calculator/Views/TitleBar.xaml
  src/Calculator/Views/TitleBar.xaml.cpp
  src/Calculator/Views/TitleBar.xaml.h
Labels: Codebase Quality
