Repository microsoft/calculator, pull requests merged in 2019-10, with the labels that each got.

#688 Update Calculator keyboard for greater consistency and extensibility
  src/CalcViewModel/Common/CalculatorButtonUser.h
  src/CalcViewModel/Common/LocalizationService.cpp
  src/CalcViewModel/Common/NavCategory.cpp
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalcViewModel/StandardCalculatorViewModel.h
  src/Calculator/App.xaml
  src/Calculator/Assets/CalcMDL2.ttf
  src/Calculator/Calculator.vcxproj
  src/Calculator/Calculator.vcxproj.filters
  src/Calculator/Controls/OperatorPanelButton.cpp
  src/Calculator/Controls/OperatorPanelButton.h
  src/Calculator/Controls/OperatorPanelListView.cpp
  src/Calculator/Controls/OperatorPanelListView.h
  src/Calculator/Resources/en-US/Resources.resw
  src/Calculator/Views/Calculator.xaml.h
  src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml
  src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml.cpp
  src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml.h
  src/Calculator/Views/CalculatorScientificAngleButtons.xaml
  src/Calculator/Views/CalculatorScientificAngleButtons.xaml.cpp
  src/Calculator/Views/CalculatorScientificAngleButtons.xaml.h
  src/Calculator/Views/CalculatorScientificOperators.xaml
  src/Calculator/Views/CalculatorScientificOperators.xaml.cpp
  src/Calculator/Views/CalculatorScientificOperators.xaml.h
  src/Calculator/Views/CalculatorStandardOperators.xaml
  src/Calculator/Views/CalculatorStandardOperators.xaml.cpp
  src/Calculator/Views/NumberPad.xaml
  src/Calculator/Views/OperatorsPanel.xaml
  src/Calculator/Views/OperatorsPanel.xaml.cpp
  src/Calculator/Views/StateTriggers/ControlSizeTrigger.cpp
  src/Calculator/Views/StateTriggers/ControlSizeTrigger.h
  src/Calculator/Views/UnitConverter.xaml
  src/CalculatorUITests/StandardModeFunctionalTests.cs
  src/Settings.XamlStyler
Labels: fixing approved issue

#638 Passive & Active tracing
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.cpp
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.h
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj
  src/GraphControl/Control/Grapher.cpp
  src/GraphControl/Control/Grapher.h
  src/GraphControl/DirectX/ActiveTracingPointRenderer.cpp
  src/GraphControl/DirectX/ActiveTracingPointRenderer.h
  src/GraphControl/DirectX/RenderMain.cpp
  src/GraphControl/DirectX/RenderMain.h
  src/GraphControl/GraphControl.vcxproj
  src/GraphControl/GraphControl.vcxproj.filters
Labels: graphing calculator

#705 Added new dev app icons and update version to 1909
  build/pipelines/azure-pipelines.release.yaml
  build/pipelines/templates/build-app-internal.yaml
  build/pipelines/templates/prepare-release-internalonly.yaml
  src/Calculator/Assets/CalculatorAppList.targetsize-256_altform-lightunplated_devicefamily-colorfulunplated.png
  src/Calculator/Assets/CalculatorAppList.targetsize-256_altform-unplated_contrast-black_devicefamily-colorfulunplated.png
  src/Calculator/Assets/CalculatorAppList.targetsize-256_altform-unplated_contrast-white_devicefamily-colorfulunplated.png
  src/Calculator/Assets/CalculatorAppList.targetsize-256_altform-unplated_devicefamily-colorfulunplated.png
  src/Calculator/Assets/CalculatorAppList.targetsize-48_altform-lightunplated_devicefamily-colorfulunplated.png
  src/Calculator/Assets/CalculatorAppList.targetsize-48_altform-unplated_contrast-black_devicefamily-colorfulunplated.png
  src/Calculator/Assets/CalculatorAppList.targetsize-48_altform-unplated_contrast-white_devicefamily-colorfulunplated.png
  src/Calculator/Assets/CalculatorAppList.targetsize-48_altform-unplated_devicefamily-colorfulunplated.png
  src/Calculator/Assets/CalculatorAppList.targetsize-96_altform-lightunplated_devicefamily-colorfulunplated.png
  src/Calculator/Assets/CalculatorAppList.targetsize-96_altform-unplated_contrast-black_devicefamily-colorfulunplated.png
  src/Calculator/Assets/CalculatorAppList.targetsize-96_altform-unplated_contrast-white_devicefamily-colorfulunplated.png
  src/Calculator/Assets/CalculatorAppList.targetsize-96_altform-unplated_devicefamily-colorfulunplated.png
  src/Calculator/Calculator.vcxproj
  src/Calculator/Calculator.vcxproj.filters
Labels: approved, design

#698 Fix the focus when right-clicking CalculationResult's TextBlock
  src/Calculator/Controls/CalculationResult.cpp
Labels: Bug, fixing approved issue

#702 Active tracing
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.cpp
  src/Calculator/Views/GraphingCalculator/GraphingCalculator.xaml.h
Labels: graphing calculator

#710 fix 505
  src/CalcManager/Ratpack/CalcErr.h
Labels: codebase quality, fixing approved issue

#687 Add E-notation support to CopyPasteManager for standard mode
  src/CalcViewModel/Common/CopyPasteManager.cpp
Labels: Bug, fixing approved issue

#685 Add fallback colors to RevealBrushes missing them
  src/Calculator/App.xaml
Labels: Bug, fixing approved issue

#686 Fix focus with AlwaysOnTop mode
  src/Calculator/Views/Calculator.xaml
  src/Calculator/Views/Calculator.xaml.cpp
  src/Calculator/Views/Calculator.xaml.h
Labels: Bug, fixing approved issue

#682 Allow users to paste expressions with ^ (power) or % (modulo)
  src/CalcViewModel/Common/CopyPasteManager.cpp
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalculatorUnitTests/CopyPasteManagerTest.cpp
Labels: Bug, fixing approved issue

#695 Do not hide expression when user presses Enter or =
  src/CalcManager/CEngine/History.cpp
  src/CalcManager/CEngine/scicomm.cpp
  src/CalcManager/CalculatorVector.h
  src/CalcManager/Header Files/CalcEngine.h
  src/CalcManager/Header Files/History.h
  src/CalcViewModel/HistoryItemViewModel.cpp
  src/CalculatorUITests/StandardModeFunctionalTests.cs
  src/CalculatorUnitTests/CalculatorManagerTest.cpp
Labels: Enhancement, fixing approved issue

#723 Updating CalculatorHistory to use a default destructor.
  src/CalcManager/CalculatorHistory.cpp
  src/CalcManager/CalculatorHistory.h
Labels: codebase quality, fixing approved issue

#727 Update release pipeline to use newer StoreBroker tasks
  build/pipelines/templates/build-app-internal.yaml
  build/pipelines/templates/prepare-release-internalonly.yaml
Labels: tooling

#733 Fix release pipeline yaml
  build/pipelines/templates/prepare-release-internalonly.yaml
Labels: tooling

#743 Allow negative numbers without digits before the decimal point to be pasted + Fix unit tests
  src/CalcViewModel/Common/CopyPasteManager.cpp
  src/CalculatorUnitTests/CopyPasteManagerTest.cpp
Labels: Bug, fixing approved issue

#745 Remove unnecessary dependencies from UITestFramework project
  src/CalculatorUITestFramework/CalculatorUITestFramework.csproj
Labels: build

#738 Make ControlSizeTrigger consistent with AdaptiveTrigger + fix conditional
  src/Calculator/Views/StateTriggers/ControlSizeTrigger.cpp
  src/Calculator/Views/StateTriggers/ControlSizeTrigger.h
Labels: codebase quality, fixing approved issue
