Repository microsoft/calculator, pull requests merged in 2020-08, with the labels that each got.

#1337 Updated the Calculator projects to include the /Z7 compiler flag
  src/CalcManager/CalcManager.vcxproj
  src/CalcViewModel/CalcViewModel.vcxproj
  src/Calculator/Calculator.vcxproj
  src/CalculatorUnitTests/CalculatorUnitTests.vcxproj
  src/GraphControl/GraphControl.vcxproj
  src/GraphingImpl/GraphingImpl.vcxproj
  src/TraceLogging/TraceLogging.vcxproj
Labels: build

#1229 Remove ICustomPropertyProviders
  src/CalcViewModel/HistoryItemViewModel.h
  src/CalcViewModel/MemoryItemViewModel.h
  src/Calculator/Views/HistoryList.xaml
  src/Calculator/Views/MemoryListItem.xaml
  src/CalculatorUITestFramework/HistoryItem.cs
  src/CalculatorUITestFramework/HistoryPanel.cs
  src/CalculatorUITestFramework/MemoryItem.cs
  src/CalculatorUITestFramework/MemoryPanel.cs
  src/CalculatorUITests/HistoryFunctionalTests.cs
  src/CalculatorUITests/MemoryFunctionalTests.cs
  src/CalculatorUITests/StandardModeFunctionalTests.cs
Labels: codebase quality

#1346 Enable keyboard entry in bit-toggling mode #478
  src/CalcViewModel/StandardCalculatorViewModel.cpp
  src/CalcViewModel/StandardCalculatorViewModel.h
  src/Calculator/Views/OperatorsPanel.xaml
Labels: fixing approved issue

#1347 'Keep on top' button appears last in the tab order (#1339)
  src/Calculator/Views/MainPage.xaml
Labels: fixing approved issue

#1312 Change the initialization time of Radio button's isChecked
  src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml
  src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml.cpp
  src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml.h
  src/Calculator/Views/OperatorsPanel.xaml.cpp
Labels: fixing approved issue
